apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    harness.io/name: {{ .Values.delegateName }}
  name: {{ .Values.delegateName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      harness.io/name: {{ .Values.delegateName }}
  template:
    metadata:
      labels:
        harness.io/name: {{ .Values.delegateName }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3460"
        prometheus.io/path: "/api/metrics"
    spec:
      serviceAccountName: {{ .Values.serviceAccount }}
      imagePullSecrets: 
        - name: dockerhub-image-pull
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      containers:
        - image: actian/harness-delegate-immutable:{{ .Values.delegateVersion }}
          imagePullPolicy: Always
          name: delegate
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3460
              scheme: HTTP
            initialDelaySeconds: 120
            periodSeconds: 10
            failureThreshold: 2
          envFrom:
            - secretRef:
                name: {{ .Values.delegateName }}-account-token
          env:
            - name: JAVA_OPTS
              value: "-Xms64M"
            - name: ACCOUNT_ID
              value: {{ .Values.harnessAccountId }}
            - name: MANAGER_HOST_AND_PORT
              value: https://app.harness.io/gratis
            - name: DEPLOY_MODE
              value: KUBERNETES
            - name: DELEGATE_NAME
              value: {{ .Values.delegateName }}
            - name: DELEGATE_TYPE
              value: "KUBERNETES"
            - name: DELEGATE_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: INIT_SCRIPT
              value: |-
                #### Adding git/bitbucket cred ######
                cat <<EOM >> $HOME/.netrc 
                machine github.com
                login {{ .Values.github_user }}
                password {{ .Values.github_token }}
                machine alm.actian.com
                login {{ .Values.bitBucket_user }}
                password {{ .Values.bitBucket_token }}
                machine bitbucket.org
                login harnessio
                password {{ .Values.bitBucket_cloud_token }}
                EOM
            - name: DELEGATE_DESCRIPTION
              value: ""
            - name: DELEGATE_TAGS
              value: ""
            - name: DELEGATE_ORG_IDENTIFIER
              value: ""
            - name: DELEGATE_PROJECT_IDENTIFIER
              value: ""
            - name: NEXT_GEN
              value: "true"
            - name: CLIENT_TOOLS_DOWNLOAD_DISABLED
              value: "true"
            - name: LOG_STREAMING_SERVICE_URL
              value: "https://app.harness.io/gratis/log-service/"
          volumeMounts:
            - mountPath: "/tmp"
              name: task-pv-storage
      volumes:
        - name: tmp-dir
          persistentVolumeClaim:
            claimName: tmp-dir