apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    harness.io/name: {{ .Values.delegateName }}
  name: {{ .Values.delegateName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 2
  selector:
    matchLabels:
      harness.io/name: {{ .Values.delegateName }}
  template:
    metadata:
      labels:
        harness.io/name: {{ .Values.delegateName }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3460"
        prometheus.io/path: "/api/metrics"
    spec:
      terminationGracePeriodSeconds: 600
      restartPolicy: Always
      containers:
      - image: harness/delegate-immutable:22.09.76614
        imagePullPolicy: Always
        name: delegate
        ports:
          - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: "4096Mi"
          requests:
            cpu: "2"
            memory: "4096Mi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3460
            scheme: HTTP
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 2
        envFrom:
        - secretRef:
            name: {{ .Values.harnessName }}-account-token
        env:
        - name: JAVA_OPTS
          value: "-Xms64M"
        - name: ACCOUNT_ID
          value: {{ .Values.harnessAccountId }}
        - name: MANAGER_HOST_AND_PORT
          value: https://app.harness.io/gratis
        - name: DEPLOY_MODE
          value: KUBERNETES
        - name: DELEGATE_NAME
          value: {{ .Values.delegateName }}
        - name: DELEGATE_TYPE
          value: "KUBERNETES"
        - name: DELEGATE_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: INIT_SCRIPT
          value: |-
            # Install software with auto approval
            apt update
            apt full-upgrade -y
            apt-get install curl apt-transport-https ca-certificates gnupg -y
            echo "deb https://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg add -
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
            curl https://packages.cloud.google.com/apt/doc/apt-key.gpg > /usr/share/keyrings/cloud.google.gpg
            apt update
            apt install git jq wget curl less unzip google-cloud-cli google-cloud-sdk-gke-gcloud-auth-plugin -y
            wget https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.16.0/kubeseal-linux-amd64 -O kubeseal
            install -m 755 kubeseal /usr/local/bin/kubeseal
            # Check git install
            git --version
            # Installing terraform with asdf
            ASDF_PATH=$HOME/.asdf
            TERRAFORM_VERSIONS="{{ .Values.TF_versions }}"
            git clone https://github.com/asdf-vm/asdf.git $ASDF_PATH
            echo ". $ASDF_PATH/asdf.sh" >> ~/.bashrc
            echo PATH=\$PATH:\$HOME/.asdf/shims:\$HOME/.asdf/bin >> /root/.bashrc
            /root/.asdf/bin/asdf --version
            export PATH=$HOME/.asdf/shims:$HOME/.asdf/bin:$PATH
            # Install and configure Terraform plugin and versions
            /root/.asdf/bin/asdf plugin-add terraform https://github.com/Banno/asdf-hashicorp.git 
            for version in $TERRAFORM_VERSIONS; do
              /root/.asdf/bin/asdf install terraform $version
            done
            # Verify Terraform versions
            /root/.asdf/bin/asdf list terraform

            # Set a default version on the delegate
            echo "terraform 1.1.7" > $HOME/.tool-versions 
            # AWS Cli
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            aws --version
            #### Adding git/bitbucket cred ######
            cat <<EOM >> $HOME/.netrc 
            machine github.com
            login {{ .Values.github_user }}
            password {{ .Values.github_token }}
            machine alm.actian.com
            login {{ .Values.bitBucket_user }}
            password {{ .Values.bitBucket_token }}
            EOM
        - name: DELEGATE_DESCRIPTION
          value: ""
        - name: DELEGATE_TAGS
          value: ""
        - name: DELEGATE_ORG_IDENTIFIER
          value: ""
        - name: DELEGATE_PROJECT_IDENTIFIER
          value: ""
        - name: NEXT_GEN
          value: "true"
        - name: CLIENT_TOOLS_DOWNLOAD_DISABLED
          value: "true"
        - name: LOG_STREAMING_SERVICE_URL
          value: "https://app.harness.io/gratis/log-service/"