# Default values for grafana-agent.

global:
  agentVersion: ""
  namespace: monitoring
  timeZone: ""
  # External labels are added automatically to each metric.
  # cloudProvider and cluster name is mandatory. 
  externalLabels: 
    cloudProvider: "GCP"
    cluster: "_test_cluster"
  environment: dev
  grafanaRegion: us
  clusterSecretStoreName: grafana-secret-store
  externalSecretName: grafana-secrets
  agentVarDirectory: "/var/lib/agent"

daemonset:
  createServiceAccount: true
  serviceAccountName: ""
  serverPort: 13579
  logLevel: info
  logFormat: json

statefulset:
  createServiceAccount: true
  serviceAccountName: ""
  serverPort: 13578
  logLevel: info
  logFormat: json

credentials:
  # <grafanaRegion>:
  #   prometheusId:
  #   lokiId:

urls:
  # <grafanaRegion>:
  #   prometheusRemoteWriteUrl:
  #   lokiUrl:

metrics:
  enabled: true
  instanceName: metrics
  scrapeInterval: 30s
  integrations:
    nodeExporter:
      collectorSet:
        - cpu
        - filesystem
        - loadavg
        - meminfo
        - netstat
  services:
    # svc_name:
    #   enabled: <true|false>
    # if enabled:
    #   releaseName:
    #   namespace:
    #   metricPath:
    #   metricPort
    # argocd:
    #   enabled: false
    # certManager:
    #   enabled: false
    # velero:
    #   enabled: false
    # externalSecrets:
    #   enabled: false
    # hashicorpVault:
    #   enabled: false
    # hashicorpConsul:
    #   enabled: false
    # ingressNginx:
    #   enabled: false
    # trivy:
    #   enabled: false
    # rabbitmq:
    #   enabled: false
  filters:
    istioEnvoyStats:
      - action: drop
        source_labels: [__name__]
        regex: istio_response_bytes_bucket|istio_request_duration_milliseconds_bucket|istio_request_bytes_bucket
    nodeExporter:
      - action: keep
        source_labels: [__name__]
        regex: node_cpu_seconds_total|node_filesystem.*|node_load.*|node_memory_MemTotal_bytes|node_memory_MemAvailable_bytes|node_memory_Buffers_bytes|node_memory_Cached_bytes|node_memory_MemFree_bytes|node_memory_Slab_bytes|node_netstat_Tcp_RetransSegs|node_netstat_Tcp_OutSegs|node_netstat_TcpExt_TCPSynRetrans|node_network_receive_bytes_total|node_network_transmit_bytes_total|node_time_seconds|node_boot_time_seconds
    kubelet: 
      - action: keep
        source_labels: [__name__]
        regex: up|kubelet_certificate_manager_client_expiration_renew_errors|kubelet_certificate_manager_client_ttl_seconds|kubelet_certificate_manager_server_ttl_seconds|kubelet_cgroup_manager_duration_seconds_bucket|kubelet_cgroup_manager_duration_seconds_count|kubelet_node_config_error|kubelet_node_name|kubelet_pleg_relist_duration_seconds_bucket|kubelet_pleg_relist_duration_seconds_count|kubelet_pleg_relist_interval_seconds_bucket|kubelet_pod_start_duration_seconds_count|kubelet_pod_worker_duration_seconds_bucket|kubelet_pod_worker_duration_seconds_count|kubelet_running_container_count|kubelet_running_containers|kubelet_running_pod_count|kubelet_running_pods|kubelet_runtime_operations_errors_total|kubelet_runtime_operations_total|kubelet_server_expiration_renew_errors|kubelet_volume_stats_used_bytes|kubelet_volume_stats_available_bytes|kubelet_volume_stats_capacity_bytes|kubelet_volume_stats_inodes|kubelet_volume_stats_inodes_used|kubernetes_build_info|node_quantile:kubelet_pleg_relist_duration_seconds:histogram_quantile|process_cpu_seconds_total|process_resident_memory_bytes|rest_client_requests_total|storage_operation_duration_seconds_count|storage_operation_errors_total|volume_manager_total_volumes
    kubeStateMetrics:
      - action: keep
        source_labels: [__name__]
        regex: up|kube_persistentvolume_status_phase|cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits|cluster:namespace:pod_cpu:active:kube_pod_container_resource_requests|cluster:namespace:pod_memory:active:kube_pod_container_resource_limits|cluster:namespace:pod_memory:active:kube_pod_container_resource_requests|kube_daemonset_status_current_number_scheduled|kube_daemonset_status_desired_number_scheduled|kube_daemonset_status_number_available|kube_daemonset_status_number_misscheduled|kube_daemonset_updated_number_scheduled|kube_deployment_metadata_generation|kube_deployment_spec_replicas|kube_deployment_status_observed_generation|kube_deployment_status_replicas|kube_deployment_status_replicas_available|kube_deployment_status_replicas_ready|kube_deployment_status_replicas_unavailable|kube_deployment_status_replicas_updated|kube_horizontalpodautoscaler_spec_max_replicas|kube_horizontalpodautoscaler_spec_min_replicas|kube_horizontalpodautoscaler_status_current_replicas|kube_horizontalpodautoscaler_status_desired_replicas|kube_job_failed|kube_job_spec_completions|kube_job_status_succeeded|kube_namespace_created|kube_node_info|kube_node_spec_taint|kube_node_spec_unschedulable|kube_node_status_allocatable|kube_node_status_capacity|kube_node_status_condition|kube_pod_container_resource_limits|kube_pod_container_resource_requests|kube_pod_container_status_ready|kube_pod_container_status_restarts_total|kube_pod_container_status_running|kube_pod_container_status_terminated|kube_pod_container_status_terminated_reason|kube_pod_container_status_waiting|kube_pod_container_status_waiting_reason|kube_pod_info|kube_pod_owner|kube_pod_status_phase|kube_replicaset_owner|kube_resourcequota|kube_statefulset_metadata_generation|kube_statefulset_replicas|kube_statefulset_status_current_revision|kube_statefulset_status_observed_generation|kube_statefulset_status_replicas|kube_statefulset_status_replicas_ready|kube_statefulset_status_replicas_updated|kube_statefulset_status_update_revision|namespace_cpu:kube_pod_container_resource_limits:sum|namespace_cpu:kube_pod_container_resource_requests:sum|namespace_memory:kube_pod_container_resource_limits:sum|namespace_memory:kube_pod_container_resource_requests:sum|namespace_workload_pod:kube_pod_owner:relabel|kube_pod_spec_volumes_persistentvolumeclaims_info
    cadvisor: 
      - action: keep
        source_labels: [__name__]
        regex: up|container_spec_memory_limit_bytes|container_cpu_cfs_periods_total|container_cpu_cfs_throttled_periods_total|container_cpu_usage_seconds_total|container_fs_usage_bytes|container_fs_limit_bytes|container_fs_reads_bytes_total|container_fs_reads_total|container_fs_writes_bytes_total|container_fs_writes_total|container_memory_cache|container_memory_rss|container_memory_swap|container_memory_working_set_bytes|container_network_receive_bytes_total|container_network_receive_packets_dropped_total|container_network_receive_packets_total|container_network_transmit_bytes_total|container_network_transmit_packets_dropped_total|container_network_transmit_packets_total|machine_memory_bytes|node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate|node_namespace_pod_container:container_memory_cache|node_namespace_pod_container:container_memory_rss|node_namespace_pod_container:container_memory_swap|node_namespace_pod_container:container_memory_working_set_bytes
    # filterName:
    # - action: <keep|drop>
    #   source_labels: [<labels list>]
    #    regex: <reg_exp>

tracing:
  enabled: false

logs:
  enabled: true
  instanceName: logs
  defaultPipelineStage: docker
  # Jobs for log scraping
  # Details will follow
