# Default values for grafana-agent.

global:
  agentVersion: ""
  namespace: monitoring
  timeZone: ""
  # External labels are added automatically to each metric.
  # cloudProvider and cluster name is mandatory. 
  externalLabels: 
    cloudProvider: "GCP"
    cluster: "_test_cluster"
  environment: dev
  grafanaRegion: us
  clusterSecretStoreName: grafana-secret-store
  externalSecretName: grafana-secrets
  agentVarDirectory: "/var/lib/agent"

daemonset:
  createServiceAccount: true
  serviceAccountName: ""
  serverPort: 13579
  logLevel: info
  logFormat: json

statefulset:
  createServiceAccount: true
  serviceAccountName: ""
  serverPort: 13578
  logLevel: info
  logFormat: json

credentials:
  # <grafanaRegion>:
  #   prometheusId:
  #   lokiId:

urls:
  # <grafanaRegion>:
  #   prometheusRemoteWriteUrl:
  #   lokiUrl:

metrics:
  enabled: true
  instanceName: metrics
  scrapeInterval: 30s
  integrations:
    nodeExporter:
      collectorSet:
        - cpu
        - filesystem
        - loadavg
        - meminfo
        - netstat
  services:
    # svc_name:
    #   enabled: <true|false>
    # if enabled:
    #   releaseName:
    #   namespace:
    #   metricPath:
    #   metricPort
    # argocd:
    #   enabled: false
    # certManager:
    #   enabled: false
    # velero:
    #   enabled: false
    # externalSecrets:
    #   enabled: false
    # hashicorpVault:
    #   enabled: false
    # hashicorpConsul:
    #   enabled: false
    # ingressNginx:
    #   enabled: false
    # trivy:
    #   enabled: false
    # rabbitmq:
    #   enabled: false
  filters:
    # filterName:
    # - action: <keep|drop>
    #   source_labels: [<labels list>]
    #    regex: <reg_exp>

tracing:
  enabled: false

logs:
  enabled: true
  instanceName: logs
  defaultPipelineStage: docker
  # Jobs for log scraping
  # Details will follow
