apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ $.Values.syntheticTests.secretName }}
  namespace: {{ $.Values.namespace }}
spec:
  refreshInterval: "60s"
  secretStoreRef:
    name: {{ $.Values.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ $.Values.syntheticTests.secretName }}
  data:
  - secretKey: prometheusUrl
    remoteRef:
      key: {{ $.Values.grafanaParameters.prometheusUrl.remoteKey }}
      property: {{ $.Values.grafanaParameters.prometheusUrl.remoteProperty }}
  - secretKey: prometheusUsername
    remoteRef:
      key: {{ $.Values.grafanaParameters.prometheusUsername.remoteKey }}
      property: {{ $.Values.grafanaParameters.prometheusUsername.remoteProperty }}
  - secretKey: prometheusPassword
    remoteRef:
      key: {{ $.Values.grafanaParameters.prometheusPassword.remoteKey }}
      property: {{ $.Values.grafanaParameters.prometheusPassword.remoteProperty }}
{{- range $test, $details := $.Values.syntheticTests.definitions }}
  - secretKey: {{ $details.usernameSecretKey }}
    remoteRef:
      key: {{ $details.usernameRemoteKey }}
      property: username
  - secretKey: {{ $details.passwordSecretKey }}
    remoteRef:
      key: {{ $details.passwordRemoteKey }}
      property: password
{{- end -}}
