---
apiVersion: v1
kind: ConfigMap
metadata:
  annotations:
    app.kubernetes.io/managed-by: cloudops
    environment: dev
    owner: cloudoperations@actian.com
  name: {{ $.Values.syntheticTests.configMapName }}
  namespace: {{ $.Values.namespace }}
{{- $root := $ }}
data:
{{- range $test, $details := $root.Values.syntheticTests.definitions }}
  {{ $details.scriptName }}: |-
{{ $.Files.Get (printf "synthetic-tests/%s" $details.scriptName) | nindent 4 }}
{{- end -}}
