{{- $environment := (include "actian.clusterEnvironment" .) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-agent-actian-modules
  labels:
    app.kubernetes.io/instance: grafana-agent
    app.kubernetes.io/component: actian-modules
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
data:
{{- if eq $environment "production" }}
  prometheus_remote_write.river: | {{ .Files.Get "files/agent-modules/actian/prometheus_remote_write_production.river" | trim | nindent 4 }}

  loki_write.river: | {{ .Files.Get "files/agent-modules/actian/loki_write_production.river" | trim | nindent 4 }}
{{- else }}
  prometheus_remote_write.river: | {{ .Files.Get "files/agent-modules/actian/prometheus_remote_write_preproduction.river" | trim | nindent 4 }}

  loki_write.river: | {{ .Files.Get "files/agent-modules/actian/loki_write_preproduction.river" | trim | nindent 4 }}
{{- end }}
