{{- if or .Values.metrics.enabled .Values.logs.enabled .Values.tracing.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-daemonset
  annotations:
{{ include "annotations.versions" . | indent 4 }}
data:
  agent.yaml: |
{{ include "agentConfig.daemonsetServer" . | indent 4}}

    metrics:
      wal_directory: "{{ .Values.global.agentVarDirectory }}/data"
      global:
        scrape_interval: {{ .Values.metrics.scrapeInterval }}
{{ include "agentConfig.externalLabels" . | indent 8 }}
{{ include "prometheus.authentication" . | indent 8 }}
      configs:
      - name: {{ .Values.metrics.instanceName }}
        host_filter: true
        scrape_configs:
{{ include "daemonsetjobs.kubernetesPods" . | indent 8 }}
{{ include "daemonsetjobs.kubernetes" . | indent 8 }}

    integrations:
{{ include "integrations.metrics" . | indent 6 }}
{{ include "integrations.nodeExporter" . | indent 6 }}

    logs:
      positions_directory: "{{ .Values.global.agentVarDirectory }}/positions"
      configs:
      - name: {{ .Values.logs.instanceName }}
{{ include "loki.authentication" . | indent 8 }}
{{ include "agentConfig.externalLabels" . | indent 10 }}
        target_config:
          sync_period: 10s
        scrape_configs:
{{ include "daemonsetjobs.kubernetesPodsLogsName" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsApp" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsDirectController" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsIndirectController" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsStatic" . | indent 8 }}
{{- end }}
