{{- if .Values.metrics.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-statefulset
data:
  agent.yaml: |
    server:
      log_format: {{ .Values.daemonset.logFormat }}
      log_level: {{ .Values.statefulset.logLevel }}
    metrics:
      wal_directory: "{{ .Values.global.agentVarDirectory }}/data"
      global:
        scrape_interval: {{ .Values.metrics.scrapeInterval }}
        external_labels:
{{- include "agentConfig.externalLabels" . | indent 8 }}
        remote_write:
{{ include "prometheus.authentication" . | indent 8 }}
      configs:
      - name: {{ .Values.metrics.instanceName }}
        host_filter: false
        scrape_configs:
{{ include "statefulsetjobs.hashicorpVault" . | indent 8 }}
{{ include "statefulsetjobs.hashicorpConsul" . | indent 8 }}
{{ include "statefulsetjobs.ingressNginx" . | indent 8 }}
{{ include "statefulsetjobs.trivy" . | indent 8 }}
{{ include "statefulsetjobs.istio" . | indent 8 }}
{{ include "statefulsetjobs.velero" . | indent 8 }}
{{ include "statefulsetjobs.argocd" . | indent 8 }}
{{ include "statefulsetjobs.certManager" . | indent 8}}
{{ include "statefulsetjobs.externalSecrets" . | indent 8}}
{{ include "statefulsetjobs.rabbitmq" . | indent 8}}
{{ include "statefulsetjobs.redpanda" . | indent 8}}
{{ include "statefulsetjobs.mimir" . | indent 8}}
{{ include "statefulsetjobs.loki" . | indent 8}}
{{ include "statefulsetjobs.grafana" . | indent 8}}
{{ include "statefulsetjobs.cadvisor" . | indent 8}}
{{ include "statefulsetjobs.kubelet" . | indent 8}}
{{ include "statefulsetjobs.kubeStateMetrics" . | indent 8}}
    integrations:
      eventhandler:
        cache_path: "{{ .Values.global.agentVarDirectory }}/eventhandler/eventhandler.cache"
        logs_instance: {{ .Values.logs.eventHandlerInstanceName }}

    logs:
      positions_directory: "{{ .Values.global.agentVarDirectory }}/eventhandler/positions"
      configs:
      - name: {{ .Values.logs.eventHandlerInstanceName }}
        clients:
{{ include "loki.authentication" . | indent 8 }}
          external_labels:
{{- include "agentConfig.externalLabels" . | indent 8 }}
            job: "integrations/kubernetes/eventhandler"
{{- end }}
