{{- if or .Values.metrics.enabled .Values.logs.enabled .Values.tracing.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-daemonset
data:
  agent.yaml: |
    server:
      log_format: {{ .Values.daemonset.logFormat }}
      log_level: {{ .Values.daemonset.logLevel }}
    metrics:
      wal_directory: "{{ .Values.global.agentVarDirectory }}/data"
      global:
        scrape_interval: {{ .Values.metrics.scrapeInterval }}
        external_labels:
{{- include "agentConfig.externalLabels" . | indent 10 }}
        remote_write:
{{ include "prometheus.authentication" . | indent 8 }}
      configs:
      - name: {{ .Values.metrics.instanceName }}
        host_filter: true
        scrape_configs:
{{ include "daemonsetjobs.kubernetesPods" . | indent 8 }}
{{ include "daemonsetjobs.kubernetes" . | indent 8 }}

    integrations:
      node_exporter:
        enabled: true
        {{- if .Values.metrics.integrations.nodeExporter.collectorSet }}
        set_collectors: 
          {{- range $set := .Values.metrics.integrations.nodeExporter.collectorSet }}
          - {{ $set }}
          {{- end }}
        {{- end }}
        {{- if .Values.metrics.filters.nodeExporter }}
        metric_relabel_configs:
          {{ range $.Values.metrics.filters.nodeExporter -}}
          - action: {{ .action }}
            source_labels: {{ .source_labels }}
            regex: {{ .regex | quote }}
          {{- end }}
        {{- end}}

    {{- if .Values.logs.enabled }}
    logs:
      positions_directory: "{{ .Values.global.agentVarDirectory }}/positions"
      configs:
      - name: {{ .Values.logs.instanceName }}
        clients:
{{ include "loki.authentication" . | indent 8 }}
          external_labels:
{{- include "agentConfig.externalLabels" . | indent 12 }}
        target_config:
          sync_period: 10s
        scrape_configs:
{{ include "daemonsetjobs.kubernetesPodsLogsName" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsApp" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsDirectController" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsIndirectController" . | indent 8 }}
{{ include "daemonsetjobs.kubernetesPodsLogsStatic" . | indent 8 }}
    {{- end }}
{{- end }}
