{{ $prometheusUserPathInVault := (include "vaultSecrets.prometheusUserPath" .) }}
{{ $prometheusUserKeyInVault := (include "vaultSecrets.prometheusUserKey" .) }}
{{ $lokiUserPathInVault := (include "vaultSecrets.lokiUserPath" .) }}
{{ $lokiUserKeyInVault := (include "vaultSecrets.lokiUserKey" .) }}
{{ $prometheusRemoteWriteUrlPathInVault := (include "vaultSecrets.prometheusRemoteWriteUrlPath" .) }}
{{ $prometheusRemoteWriteUrlKeyInVault := (include "vaultSecrets.prometheusRemoteWriteUrlKey" .) }}
{{ $lokiWriteUrlPathInVault := (include "vaultSecrets.lokiWriteUrlPath" .) }}
{{ $lokiWriteUrlKeyInVault := (include "vaultSecrets.lokiWriteUrlKey" .) }}
{{ $prometheusPasswordPathInVault := (include "vaultSecrets.prometheusPasswordPath" .) }}
{{ $prometheusPasswordKeyInVault := (include "vaultSecrets.prometheusPasswordKey" .) }}
{{ $lokiPasswordPathInVault := (include "vaultSecrets.lokiPasswordPath" .) }}
{{ $lokiPasswordKeyInVault := (include "vaultSecrets.lokiPasswordKey" .) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.externalSecretName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.global.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.externalSecretName }}
  data:
  - secretKey: prometheus-user
    remoteRef:
      key: {{ $prometheusUserPathInVault }}
      property: {{ $prometheusUserKeyInVault}}
  - secretKey: loki-user
    remoteRef:
      key: {{ $lokiUserPathInVault}}
      property: {{ $lokiUserKeyInVault}}
  - secretKey: prometheus-remote-write-url
    remoteRef:
      key: {{ $prometheusRemoteWriteUrlPathInVault}}
      property: {{ $prometheusRemoteWriteUrlKeyInVault}}
  - secretKey: loki-write-url
    remoteRef:
      key: {{ $lokiWriteUrlPathInVault}}
      property: {{ $lokiWriteUrlKeyInVault}}
  - secretKey: prometheus-password
    remoteRef:
      key: {{ $prometheusPasswordPathInVault }}
      property: {{ $prometheusPasswordKeyInVault }}
  - secretKey: loki-password
    remoteRef:
      key: {{ $lokiPasswordPathInVault }}
      property: {{ $lokiPasswordKeyInVault }}
