{{ $prometheusPasswordPathInVault := (include "vaultSecrets.prometheusPasswordPath" .) }}
{{ $prometheusPasswordKeyInVault := (include "vaultSecrets.prometheusPasswordKey" .) }}
{{ $lokiPasswordPathInVault := (include "vaultSecrets.lokiPasswordPath" .) }}
{{ $lokiPasswordKeyInVault := (include "vaultSecrets.lokiPasswordKey" .) }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.global.externalSecretName }}
  namespace: {{ .Values.global.namespace }}
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: {{ .Values.global.clusterSecretStoreName }}
    kind: ClusterSecretStore
  target:
    name: {{ .Values.global.externalSecretName }}
  data:
  - secretKey: mimir-password
    remoteRef:
      key: {{ $prometheusPasswordPathInVault }}
      property: {{ $prometheusPasswordKeyInVault }}
  - secretKey: loki-password
    remoteRef:
      key: {{ $lokiPasswordPathInVault }}
      property: {{ $lokiPasswordKeyInVault }}
