{{ $statefulServiceAccountName := (include "statefulset.ServiceAccountName" .) }}
{{ $daemonsetServiceAccountName := (include "daemonset.ServiceAccountName" .) }}
{{- if .Values.statefulset.createServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $statefulServiceAccountName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $statefulServiceAccountName }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - events
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $statefulServiceAccountName }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $statefulServiceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ $statefulServiceAccountName }}
  namespace: {{ .Values.global.namespace }}
{{- end -}}
{{- if and (.Values.daemonset.createServiceAccount) (ne $statefulServiceAccountName $daemonsetServiceAccountName ) -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $daemonsetServiceAccountName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ $daemonsetServiceAccountName }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/proxy
  - services
  - endpoints
  - pods
  - events
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - /metrics
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ $daemonsetServiceAccountName }}
  annotations:
{{ include "annotations.versions" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ $daemonsetServiceAccountName }}
subjects:
- kind: ServiceAccount
  name: {{ $daemonsetServiceAccountName }}
  namespace: {{ .Values.global.namespace }}
{{- end -}}
